language: java
install: skip
jdk:
  - openjdk8
before_script:
  - "gem install travis-artifacts"
script: 
  - "./gradlew clean packDeb"
after_script:
addons:
  artifacts: true
  paths:
    - $HOME/build/distributions/*.deb
