language: java
install: skip
jdk:
  - openjdk8
before_script:
  - "gem install travis-artifacts"
script: 
  - "./gradlew clean packDeb"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET_NAME
  region: $AWS_REGION_NAME
  skip_cleanup: true
  upload-dir: build/distributions/

