language: java
install: skip
jdk:
  - openjdk8
before_script:
  - "gem install travis-artifacts"
script: 
  - "./gradlew clean packDeb"
after_success: # and this only on success
  - "travis-artifacts upload --path build/distributions/*.deb"
