language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
  - gem install travis-artifacts
after_script:
  - addons:
      artifacts:
        s3_region: "us-west-2"
        path: build/distributions/*.deb 
