language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
deploy:
  provider: s3
  access_key_id: ${access_key_id}
  secret_access_key: ${secret_key_id}
  bucket: "S3 Bucket"
  skip_cleanup: true
