language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
  - gem install deb-s3
  - deb-s3 upload --bucket debian-repo-spinnaker --arch amd64 --codename trusty \
 --preserve-versions true build/distributions/*.deb --s3-region=us-west-2
