language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
  - gem install travis-artifacts
  - gem install deb-s3
  - deb-s3 upload --bucket debian-repo-spinnaker --access-key-id $ACCESS_KEY_ID --secret-access-key $SECRET_ACCESS_KEY --arch amd64 --codename trusty --preserve-versions true build/distributions/*.deb --s3-region=us-west-2
after_script:
  - travis-artifacts upload --path build/distributions/*.deb
