language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
after_script:
  - "curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash"
  - artifacts upload

