language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
  - gem install deb-s3
after_script:
  - deb-s3 upload --bucket debian-repo-spinnaker --access-key-id $AWS_ACCESS_KEY_ID --secret-access-key $AWS_SECRET_ACCESS_KEY --arch amd64 --codename trusty --preserve-versions true build/distributions/*.deb --s3-region=us-west-2

