language: java
install: skip
jdk:
  - openjdk8
script: 
  - ./gradlew clean packDeb
  - gem install travis-artifacts
after_script:
  - travis-artifacts upload --path build/distributions/*.deb --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket debian-repo-spinnaker
